services:
  activemq:
    image: rmohr/activemq:latest
    container_name: activemq
    ports:
      - "8161:8161"
      - "61616:61616"
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
    volumes:
      - activemq_data:/opt/activemq/data
    networks:
      - balance_network

  mysql:
    image: mysql:latest
    container_name: balance_db_container
    environment:
      MYSQL_ROOT_PASSWORD: denis123
      MYSQL_DATABASE: balance_db
    ports:
      - "3306:3306"
    volumes:
      - balance_db_data:/var/lib/mysql
    networks:
      - balance_network

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: balance_keycloak
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT: false
      KC_HOSTNAME_STRICT_HTTPS: false
      JAVA_OPTS: "-Xms512m -Xmx1024m -XX:MetaspaceSize=96M -XX:MaxMetaspaceSize=256m"
      JAVA_OPTS_APPEND: "-Djava.awt.headless=true"
    ports:
      - "8081:8080"
    command:
      - start-dev
      - --hostname-strict=false
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:8080/realms/balance-realm/.well-known/openid-configuration" ]
      interval: 10s
      timeout: 10s
      retries: 20
      start_period: 40s
    networks:
      - balance_network

  app:
    build: .
    container_name: balance_app
    depends_on:
      - mysql
      - activemq
      - keycloak  # добавьте keycloak в depends_on
    ports:
      - "8084:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/balance_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: denis123
      KEYCLOAK_URL: http://keycloak:8080
    networks:
      - balance_network

  prometheus:
    image: prom/prometheus:latest
    container_name: balance_prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
      - '--web.console.libraries=/etc/prometheus/console_libraries'
      - '--web.console.templates=/etc/prometheus/consoles'
      - '--storage.tsdb.retention.time=200h'
      - '--web.enable-lifecycle'
    networks:
      - balance_network

  grafana:
    image: grafana/grafana:latest
    container_name: balance_grafana
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    volumes:
      - ./grafana/provisioning:/etc/grafana/provisioning
      - grafana_data:/var/lib/grafana
    depends_on:
      - prometheus
    networks:
      - balance_network

volumes:
  activemq_data:
  balance_db_data:
  prometheus_data:
  grafana_data:

networks:
  balance_network:
    driver: bridge